/**
 * Phase 9 — FIRST-WRITE APPLY PLAN (PLAN ONLY, NO WRITES).
 *
 * Reads the consolidated review package and produces a concrete plan for the
 * first real write of the new mikveh records into the app dataset. It does NOT
 * write to the DB, does NOT publish, does NOT modify app data or schema — it
 * only emits two planning artifacts. All COUNTS are derived from the live
 * package so the plan can't drift from reality.
 *
 * Run:  node importers/mikvahs/first-write-plan.ts
 * Out:  output/first-write-apply-plan.json
 *       output/first-write-apply-summary.json
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { isMain } from '../shared/utils.ts';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, 'output');
const readJson = <T>(f: string): T => JSON.parse(readFileSync(join(OUT, f), 'utf8')) as T;

interface PkgRecord {
  sourceSystem: string; city: string | null; address: string | null;
  record: { location?: unknown };
}

function run(): void {
  const pkg = readJson<PkgRecord[]>('unified-new-mikveh-review-package.json');
  const writeReady = pkg.filter((p) => p.record.location != null);
  const blocked = pkg.filter((p) => p.record.location == null);

  const bySystem = (rows: PkgRecord[]) => rows.reduce<Record<string, number>>((a, p) => { a[p.sourceSystem] = (a[p.sourceSystem] ?? 0) + 1; return a; }, {});
  const byCity = (rows: PkgRecord[]) => rows.reduce<Record<string, number>>((a, p) => { const c = p.city ?? '?'; a[c] = (a[c] ?? 0) + 1; return a; }, {});
  const readyMissingAddress = writeReady.filter((p) => !p.address || !String(p.address).trim()).length;

  // ----- schema support verification (read from the app, verified in this phase) -----
  const schemaSupport = {
    placeTypeIncludesMikveh: true,
    evidence: "src/types/place.ts:8 — PlaceType = 'restaurant' | 'synagogue' | 'mikveh'",
    uiLabel: "src/utils/placeType.ts — placeTypeLabel.mikveh = 'מקווה' ✓",
    uiIcon: "src/utils/placeType.ts — placeTypeIcon.mikveh = 'water' ✓",
    uiFilter: 'src/types/filters.ts — PlaceFilters.placeType: PlaceType | null accepts mikveh ✓',
    verdict: 'TYPE-SYSTEM & UI READY for mikveh — no PlaceType change required.',
  };

  // ----- blockers -----
  const blockers = [
    {
      id: 'B1', severity: 'blocker', kind: 'pipeline',
      what: "importers/shared/database.ts — APP_TYPES = ['synagogue','restaurant'] EXCLUDES 'mikveh', so rebuildAppDataset() drops every mikveh record.",
      fix: "Add 'mikveh' to APP_TYPES (line 26). Do NOT change yet.",
    },
    {
      id: 'B2', severity: 'blocker', kind: 'data',
      what: `Place.location is REQUIRED, but ${blocked.length}/${pkg.length} records (all municipal/א.ש בינה) have NO native coordinates. They cannot become valid Place records until geocoded.`,
      fix: 'Defer these to a geocoding gate (offline cached geocoder) → re-dedup → second write. Only the coordinate-bearing records go in the FIRST write.',
    },
    {
      id: 'B3', severity: 'blocker', kind: 'code',
      what: 'No mapper converts a unified NormalizedImportRecord → app Place for these council/municipal records. mapMikvahToPlace.ts only accepts the datagov GeocodedMikvah shape.',
      fix: 'Add importers/shared/mapUnifiedMikvahToPlace.ts (id, name, type:mikveh, cityId←cityHint, address←address||cityHint||"", location, source:"seed", phone, openingHours, tags). Do NOT create yet.',
    },
    {
      id: 'B4', severity: 'note', kind: 'fidelity',
      what: 'Place has no `extra` field, so mikveh-specific data (gender/category, balanit/attendant, sourceUrl, council provenance) would be DROPPED on write. Place.source enum is only osm|seed → council/municipal collapses to "seed".',
      fix: 'OPTIONAL: extend Place with an optional `extra`/mikveh fields, or accept the loss for v1. Decide before write.',
    },
    {
      id: 'B5', severity: 'note', kind: 'naming',
      what: "CATEGORY_FILES['mikveh'] = 'mikvahs.datagov.json' — a misleading name for council/municipal records (and would collide if gov mikvahs are later published to the same file).",
      fix: "OPTIONAL: rename to a neutral 'mikvahs.json' or support multiple mikveh source files before write.",
    },
  ];

  // ----- files that WOULD be modified (NOT modified now) -----
  const filesToModify = [
    { path: 'importers/shared/database.ts', change: "add 'mikveh' to APP_TYPES (line 26)", type: 'edit-existing' },
    { path: 'importers/shared/mapUnifiedMikvahToPlace.ts', change: 'NEW mapper: NormalizedImportRecord → Place', type: 'create-new' },
    { path: 'src/data/generated/mikvahs.json', change: 'NEW generated category file holding the mikveh Place records (additive)', type: 'create-generated' },
    { path: 'src/data/generated/places.osm.json', change: 'REGENERATED by rebuildAppDataset() (the app dataset) — not hand-edited', type: 'regenerated' },
    { path: 'src/data/generated/cities.osm.json', change: 'REGENERATED by rebuildAppDataset() — adds mikveh cities', type: 'regenerated' },
    { path: 'src/types/place.ts', change: 'OPTIONAL: add `extra`/mikveh fields (only if preserving gender/balanit/sourceUrl)', type: 'optional' },
    { path: 'src/screens/HomeScreen.tsx', change: 'OPTIONAL: add a "מקווה" shortcut/entry point if not already present', type: 'optional' },
  ];

  // ----- write order (phased: ready first, blocked after geocoding) -----
  const writeOrder = [
    '0. PRE: create backup src/data/generated/places.osm.pre-mikveh.backup.json (matches existing pre-step1/precouncils convention).',
    `1. WRITE 1 (ready now): map the ${writeReady.length} coordinate-bearing records → Place JSON via the new mapper.`,
    "2. add 'mikveh' to APP_TYPES in database.ts; write the mikveh category file (src/data/generated/mikvahs.json).",
    '3. run rebuildAppDataset() → regenerates places.osm.json + cities.osm.json WITH the mikveh records.',
    '4. run post-write validation checks (below). If any fail → rollback.',
    `5. WRITE 2 (deferred): geocode the ${blocked.length} coordless records (offline cached geocoder) → re-run dedup vs the now-published set → map resolved ones → repeat steps 2-4 additively.`,
    '6. ONLY AFTER both writes validate: process the held enrich/manual/geocoding-needed items, then national aggregators.',
  ];

  const rollbackPlan = [
    'Additive-only design: every new record has a fresh id and no existing place id is touched → rollback is removal, not repair.',
    '1. restore src/data/generated/places.osm.json from places.osm.pre-mikveh.backup.json (and cities.osm.json similarly).',
    "2. revert the database.ts APP_TYPES edit (git checkout importers/shared/database.ts).",
    '3. delete src/data/generated/mikvahs.json (the new category file).',
    '4. re-run rebuildAppDataset() to confirm the dataset matches the pre-write backup (diff record count + ids).',
    '5. git status / git diff to confirm no stray app-data changes remain.',
  ];

  const postWriteChecks = [
    `places.osm.json record count increased by EXACTLY ${writeReady.length} (write 1); no pre-existing id removed or modified (diff old vs new id sets).`,
    'every new record: valid location (lat 29.3–33.5, lng 34.2–35.95), non-empty name, type==="mikveh", non-empty cityId.',
    'no id collision between new mikveh ids and existing place ids.',
    'cities.osm.json contains the new mikveh cities; counts re-sorted correctly.',
    'npx tsc -p importers/tsconfig.json --noEmit passes; app typecheck/build passes.',
    "app smoke test: mikveh pins render with the 'water' icon, the מקווה filter returns them, detail screen opens.",
  ];

  const approvalChecklist = [
    'Reviewer approved the 110-record package (Phase 8 review).',
    `Confirmed additive-only: the write adds ${writeReady.length} new ids and modifies/removes 0 existing places.`,
    `Decided Tier-B handling: geocode-then-write the ${blocked.length} coordless records as a SEPARATE second write (not in write 1).`,
    'Approved the database.ts APP_TYPES change and the new mapper (B1, B3).',
    'Backup of places.osm.json created (step 0).',
    'Decided B4 (drop mikveh-specific fields vs extend Place) and B5 (category file name).',
    'Post-write validation checks defined and ready to run.',
    'EXPLICIT GO for the first write given by a human.',
  ];

  const plan = {
    generatedNote: 'PHASE 9 — APPLY PLAN ONLY. No DB write, no publish, no app-data or schema change performed. This document describes what a future, approved write would do.',
    source: 'importers/mikvahs/output/unified-new-mikveh-review-package.json',
    canonicalType: 'mikveh',
    schemaSupport,
    blockers,
    writeTiers: {
      tierA_writeReady: { count: writeReady.length, reason: 'native coordinates present', bySystem: bySystem(writeReady), byCity: byCity(writeReady), missingAddressFallbackToCity: readyMissingAddress },
      tierB_blockedPendingGeocode: { count: blocked.length, reason: 'no coordinates → Place.location required', bySystem: bySystem(blocked), byCity: byCity(blocked) },
    },
    filesToModify,
    writeOrder,
    rollbackPlan,
    postWriteChecks,
    approvalChecklist,
    dryRun: true, liveDataTouched: false, publishPerformed: false, schemaChanged: false,
  };

  const summary = {
    generatedNote: 'PHASE 9 — first-write apply SUMMARY. Plan only; nothing written or published.',
    recordsToAdd: { total: pkg.length, writeReadyNow: writeReady.length, deferredPendingGeocode: blocked.length },
    schemaBlockers: blockers.filter((b) => b.severity === 'blocker').map((b) => `${b.id}: ${b.what}`),
    schemaNotes: blockers.filter((b) => b.severity === 'note').map((b) => `${b.id}: ${b.what}`),
    schemaSupportVerdict: schemaSupport.verdict,
    filesThatWouldBeModified: filesToModify.map((f) => `${f.path} (${f.type}) — ${f.change}`),
    writeOrder,
    rollbackPlan,
    postWriteValidationChecks: postWriteChecks,
    finalApprovalChecklist: approvalChecklist,
    recordsByCityWriteReady: byCity(writeReady),
    estimatedNationalTotal: { afterWrite1: 606 + writeReady.length, afterWrite2: 606 + pkg.length, note: `write 1 adds ${writeReady.length} (coordinate-bearing) → ~${606 + writeReady.length}; write 2 adds ${blocked.length} after geocoding → ~${606 + pkg.length}.` },
    nextStep: 'Obtain explicit human GO, then execute write 1 (Tier A) per writeOrder. Do NOT proceed without sign-off on the approval checklist.',
    dryRun: true, liveDataTouched: false, publishPerformed: false,
  };

  writeFileSync(join(OUT, 'first-write-apply-plan.json'), JSON.stringify(plan, null, 2), 'utf8');
  writeFileSync(join(OUT, 'first-write-apply-summary.json'), JSON.stringify(summary, null, 2), 'utf8');

  console.log('=== Phase 9 first-write apply plan (PLAN ONLY) ===');
  console.log(`package=${pkg.length} | write-ready(Tier A)=${writeReady.length} | blocked-no-coords(Tier B)=${blocked.length}`);
  console.log(`schema: PlaceType includes mikveh = YES; UI label/icon/filter = YES`);
  console.log(`blockers: ${blockers.filter((b) => b.severity === 'blocker').map((b) => b.id).join(', ')} | notes: ${blockers.filter((b) => b.severity === 'note').map((b) => b.id).join(', ')}`);
  console.log(`national est: write1 ~${606 + writeReady.length}, write2 ~${606 + pkg.length}`);
}

if (isMain(import.meta.url)) run();
