#!/usr/bin/env node
/**
 * Post-processes `expo export --platform web` output into a real, installable,
 * offline-capable PWA.
 *
 * Expo's generated index.html is deliberately minimal. Everything a Hebrew RTL
 * web app needs on top of it is added here:
 *
 *   • dir="rtl" on <html>            — app.json declares it, the export drops it
 *   • manifest.webmanifest           — without it Android cannot install the app
 *   • service worker                 — the whole dataset is already in the
 *                                      bundle, so the app can work fully offline;
 *                                      nothing was taking advantage of that
 *   • Open Graph / Twitter cards     — shared links were rendering blank
 *   • apple-touch-icon + meta        — iOS "Add to Home Screen"
 *
 * Idempotent: safe to run twice on the same dist/.
 */

import { readFileSync, writeFileSync, copyFileSync, readdirSync, existsSync } from 'node:fs';
import { resolve, dirname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const dist = resolve(root, 'dist');

if (!existsSync(dist)) {
  console.error('✖ dist/ not found — run `npx expo export --platform web` first.');
  process.exit(1);
}

const APP_NAME = 'קרוב';
const APP_DESCRIPTION = 'מוצא לך מקומות כשרים קרובים אליך — מסעדות, בתי כנסת, מקוואות ועוד';
const THEME_COLOR = '#1E7A46';
const BACKGROUND_COLOR = '#0F3D22';
const ORIGIN = 'https://karov-eta.vercel.app';

// ── Icons ─────────────────────────────────────────────────────────────────────

const icons = [
  ['assets/icon.png', 'icon-1024.png'],
  ['assets/favicon.png', 'icon-196.png'],
  ['assets/android-icon-foreground.png', 'icon-maskable.png'],
];

for (const [from, to] of icons) {
  const src = resolve(root, from);
  if (existsSync(src)) copyFileSync(src, resolve(dist, to));
}
// Historical name — some iOS versions look for it at the root by convention.
if (existsSync(resolve(root, 'assets/icon.png'))) {
  copyFileSync(resolve(root, 'assets/icon.png'), resolve(dist, 'apple-touch-icon.png'));
}

// ── Manifest ──────────────────────────────────────────────────────────────────

const manifest = {
  name: 'קרוב — כל מה שיהודי צריך, קרוב אליך',
  short_name: APP_NAME,
  description: APP_DESCRIPTION,
  lang: 'he',
  dir: 'rtl',
  start_url: '/',
  scope: '/',
  display: 'standalone',
  orientation: 'portrait',
  theme_color: THEME_COLOR,
  background_color: BACKGROUND_COLOR,
  categories: ['food', 'travel', 'lifestyle'],
  icons: [
    { src: '/icon-196.png', sizes: '196x196', type: 'image/png', purpose: 'any' },
    { src: '/icon-1024.png', sizes: '1024x1024', type: 'image/png', purpose: 'any' },
    { src: '/icon-maskable.png', sizes: '1024x1024', type: 'image/png', purpose: 'maskable' },
  ],
  shortcuts: [
    { name: 'מה יש סביבי?', url: '/around' },
    { name: 'זמני היום', url: '/zmanim' },
    { name: 'מועדפים', url: '/favorites' },
  ],
};

writeFileSync(resolve(dist, 'manifest.webmanifest'), JSON.stringify(manifest, null, 2), 'utf8');

// ── Service worker ────────────────────────────────────────────────────────────

/** Collect the hashed JS bundles so the precache list matches this exact build. */
const jsDir = resolve(dist, '_expo/static/js/web');
const bundles = existsSync(jsDir)
  ? readdirSync(jsDir)
      .filter((f) => f.endsWith('.js'))
      .map((f) => `/_expo/static/js/web/${f}`)
  : [];

// The bundle hash doubles as the cache version — a new build evicts the old one.
const version = bundles.length ? basename(bundles[0]).replace(/^index-|\.js$/g, '') : 'dev';

const precache = ['/', '/index.html', '/manifest.webmanifest', '/icon-196.png', ...bundles];

const sw = `/* Generated by scripts/patch-pwa.mjs — do not edit. */
const VERSION = '${version}';
const CACHE = 'karov-' + VERSION;
const PRECACHE = ${JSON.stringify(precache, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      // addAll rejects the whole batch if any single request fails, which would
      // leave the app with no worker at all. Take what we can get.
      .then((cache) => Promise.allSettled(PRECACHE.map((url) => cache.add(url))))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);

  // Cross-origin (hebcal, sefaria, tile servers, unpkg) is left entirely alone:
  // caching opaque responses costs storage and can serve stale halachic times.
  if (url.origin !== self.location.origin) return;

  // Navigations: network first so a deploy is picked up immediately, falling
  // back to the cached shell so the app still opens with no connection.
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request).catch(() => caches.match('/index.html').then((r) => r || Response.error())),
    );
    return;
  }

  // Static assets are content-hashed, so a cache hit is always correct.
  event.respondWith(
    caches.match(request).then(
      (cached) =>
        cached ||
        fetch(request).then((response) => {
          if (response.ok && response.type === 'basic') {
            const copy = response.clone();
            caches.open(CACHE).then((cache) => cache.put(request, copy));
          }
          return response;
        }),
    ),
  );
});
`;

writeFileSync(resolve(dist, 'sw.js'), sw, 'utf8');

// ── index.html ────────────────────────────────────────────────────────────────

const htmlPath = resolve(dist, 'index.html');
let html = readFileSync(htmlPath, 'utf8');

// app.json declares "dir": "rtl" but the export does not emit it.
if (!/<html[^>]*\sdir=/i.test(html)) {
  html = html.replace(/<html([^>]*)>/i, '<html$1 dir="rtl">');
}

const HEAD_MARKER = '<!-- karov:pwa -->';
if (!html.includes(HEAD_MARKER)) {
  const head = [
    HEAD_MARKER,
    '<link rel="manifest" href="/manifest.webmanifest" />',
    `<meta name="theme-color" content="${THEME_COLOR}" />`,
    `<meta name="description" content="${APP_DESCRIPTION}" />`,

    '<link rel="apple-touch-icon" href="/apple-touch-icon.png" />',
    '<meta name="apple-mobile-web-app-capable" content="yes" />',
    '<meta name="mobile-web-app-capable" content="yes" />',
    '<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />',
    `<meta name="apple-mobile-web-app-title" content="${APP_NAME}" />`,

    '<meta property="og:type" content="website" />',
    `<meta property="og:site_name" content="${APP_NAME}" />`,
    `<meta property="og:title" content="${APP_NAME} — כל מה שיהודי צריך, קרוב אליך" />`,
    `<meta property="og:description" content="${APP_DESCRIPTION}" />`,
    `<meta property="og:url" content="${ORIGIN}/" />`,
    `<meta property="og:image" content="${ORIGIN}/icon-1024.png" />`,
    '<meta property="og:locale" content="he_IL" />',
    '<meta name="twitter:card" content="summary" />',
    `<meta name="twitter:title" content="${APP_NAME}" />`,
    `<meta name="twitter:description" content="${APP_DESCRIPTION}" />`,
    `<meta name="twitter:image" content="${ORIGIN}/icon-1024.png" />`,
  ].join('\n    ');

  html = html.replace('</head>', `    ${head}\n  </head>`);
}

const SW_MARKER = 'karov:sw-register';
if (!html.includes(SW_MARKER)) {
  const register = `    <script id="${SW_MARKER}">
      if ('serviceWorker' in navigator) {
        window.addEventListener('load', function () {
          navigator.serviceWorker.register('/sw.js').catch(function () {
            /* offline support is a bonus, never a hard requirement */
          });
        });
      }
    </script>`;
  html = html.replace('</body>', `${register}\n  </body>`);
}

writeFileSync(htmlPath, html, 'utf8');

console.log('PWA post-processing complete');
console.log('  manifest.webmanifest  ' + manifest.icons.length + ' icons, ' + manifest.shortcuts.length + ' shortcuts');
console.log('  sw.js                 version ' + version + ', ' + precache.length + ' precached entries');
console.log('  index.html            dir=rtl, manifest, OG/Twitter, apple-touch-icon, SW registration');
